# Generated by Django 6.0.2 on 2026-02-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(default='Budget Ndio Story', max_length=255)),
                ('consortium_name', models.CharField(default='BNSCLIENT1', max_length=100)),
                ('tagline', models.CharField(default='Follow the Budget. Find the Story.', max_length=255)),
                ('brand_promise', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('vision', models.TextField(blank=True)),
                ('mission', models.TextField(blank=True)),
                ('headquarters', models.CharField(default='Nairobi, Kenya', max_length=255)),
                ('registration_country', models.CharField(default='Kenya', max_length=100)),
                ('year_established', models.PositiveSmallIntegerField(default=2024)),
                ('email_general', models.EmailField(blank=True, max_length=254)),
                ('email_partnerships', models.EmailField(blank=True, max_length=254)),
                ('email_media', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('tiktok', models.CharField(blank=True, max_length=100)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('twitter', models.CharField(blank=True, max_length=100)),
                ('youtube', models.CharField(blank=True, max_length=100)),
                ('facebook', models.CharField(blank=True, max_length=100)),
                ('primary_color', models.CharField(default='#0066CC', max_length=7)),
                ('secondary_color', models.CharField(default='#00A6A6', max_length=7)),
                ('alert_color', models.CharField(default='#FF6B35', max_length=7)),
                ('success_color', models.CharField(default='#2ECC71', max_length=7)),
                ('neutral_dark', models.CharField(default='#1A1A2E', max_length=7)),
                ('neutral_light', models.CharField(default='#F8F9FA', max_length=7)),
                ('countries_reached', models.PositiveIntegerField(default=47)),
                ('budget_reports_analyzed', models.PositiveIntegerField(default=500)),
                ('citizens_engaged', models.PositiveIntegerField(default=15000)),
                ('youth_champion_trainings', models.PositiveIntegerField(default=120)),
                ('partner_organizations', models.PositiveIntegerField(default=200)),
                ('programs_delivered', models.PositiveIntegerField(default=120)),
                ('is_independent', models.BooleanField(default=True)),
                ('is_non_partisan', models.BooleanField(default=True)),
                ('document_version', models.CharField(default='1.0', max_length=20)),
                ('last_updated', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization Profile',
                'verbose_name_plural': 'Organization Profiles',
                'db_table': 'accounts_organization_profile',
            },
        ),
    ]
