# Generated by Django 6.0.2 on 2026-02-22 10:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#0066CC', max_length=7)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'content_category',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
                ('source_url', models.URLField(blank=True)),
                ('is_breaking', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'content_newsitem',
                'ordering': ['-is_breaking', '-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, upload_to='playlists/')),
                ('is_featured', models.BooleanField(default=False)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'content_playlist',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('platform', models.CharField(choices=[('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('x', 'X (Twitter)'), ('facebook', 'Facebook'), ('instagram', 'Instagram')], max_length=20)),
                ('external_id', models.CharField(max_length=255)),
                ('external_url', models.URLField()),
                ('embed_url', models.URLField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('content_type', models.CharField(choices=[('budget_basics', 'Budget Basics'), ('finance_bill', 'Finance Bill'), ('national_budget', 'National Budget'), ('county_budget', 'County Budget'), ('sector_deep_dive', 'Sector Deep Dive'), ('tracker_story', 'Tracker Story'), ('youth_voice', 'Youth Voice')], max_length=20)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('view_count', models.PositiveBigIntegerField(default=0)),
                ('like_count', models.PositiveBigIntegerField(default=0)),
                ('share_count', models.PositiveBigIntegerField(default=0)),
                ('comment_count', models.PositiveBigIntegerField(default=0)),
                ('last_metrics_update', models.DateTimeField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, to='content.category')),
                ('playlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='content.playlist')),
                ('sponsored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsored_videos', to='accounts.sponsorprofile')),
            ],
            options={
                'db_table': 'content_video',
                'ordering': ['-is_featured', '-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('excerpt', models.TextField(blank=True, max_length=500)),
                ('content', models.TextField(blank=True)),
                ('content_html', models.TextField(blank=True)),
                ('post_type', models.CharField(choices=[('investigation', 'Investigation'), ('explainer', 'Explainer'), ('update', 'Update'), ('field_report', 'Field Report'), ('opinion', 'Opinion'), ('sponsored', 'Sponsored Content')], max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('featured_image', models.ImageField(blank=True, upload_to='blog/featured/')),
                ('featured_image_caption', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_publish_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveBigIntegerField(default=0)),
                ('read_time_minutes', models.PositiveSmallIntegerField(default=5)),
                ('allow_comments', models.BooleanField(default=True)),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('og_image', models.ImageField(blank=True, upload_to='blog/og/')),
                ('search_vector', models.TextField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('co_authors', models.ManyToManyField(blank=True, related_name='co_authored_posts', to=settings.AUTH_USER_MODEL)),
                ('related_posts', models.ManyToManyField(blank=True, to='content.blogpost')),
                ('sponsored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsored_posts', to='accounts.sponsorprofile')),
                ('categories', models.ManyToManyField(blank=True, to='content.category')),
                ('related_videos', models.ManyToManyField(blank=True, to='content.videocontent')),
            ],
            options={
                'db_table': 'content_blogpost',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='videocontent',
            index=models.Index(fields=['platform', 'is_published'], name='content_vid_platfor_cb9399_idx'),
        ),
        migrations.AddIndex(
            model_name='videocontent',
            index=models.Index(fields=['content_type', 'is_published'], name='content_vid_content_71e9f1_idx'),
        ),
        migrations.AddIndex(
            model_name='videocontent',
            index=models.Index(fields=['-published_at'], name='content_vid_publish_ad99bf_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['status', '-published_at'], name='content_blo_status_b5b42b_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['post_type', 'status'], name='content_blo_post_ty_c793dd_idx'),
        ),
    ]
