# Generated by Django 6.0.2 on 2026-02-22 10:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('content', '0001_initial'),
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer'), ('card', 'Credit/Debit Card'), ('paypal', 'PayPal'), ('crypto', 'Cryptocurrency')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=255)),
                ('payment_provider', models.CharField(blank=True, max_length=50)),
                ('payment_metadata', models.JSONField(blank=True, default=dict)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurring_frequency', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('receipt_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('receipt_sent', models.BooleanField(default=False)),
                ('campaign_source', models.CharField(blank=True, max_length=100)),
                ('landing_page', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='accounts.donorprofile')),
                ('parent_donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_instances', to='sponsors.donation')),
            ],
            options={
                'db_table': 'sponsors_donation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SponsorAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='sponsors/assets/')),
                ('asset_type', models.CharField(choices=[('logo', 'Logo'), ('guidelines', 'Brand Guidelines'), ('ad_creative', 'Ad Creative'), ('photo', 'Photo'), ('other', 'Other')], max_length=50)),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='accounts.sponsorprofile')),
            ],
            options={
                'db_table': 'sponsors_asset',
            },
        ),
        migrations.CreateModel(
            name='SponsorshipDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliverable_type', models.CharField(choices=[('logo_display', 'Logo Display'), ('dedicated_content', 'Dedicated Content'), ('event_presence', 'Event Presence'), ('newsletter_mention', 'Newsletter Mention'), ('social_shoutout', 'Social Media Shoutout')], max_length=20)),
                ('description', models.TextField()),
                ('quantity_required', models.PositiveIntegerField(default=1)),
                ('quantity_delivered', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('due_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_content', models.ManyToManyField(blank=True, related_name='sponsor_deliverables', to='content.blogpost')),
                ('linked_newsletters', models.ManyToManyField(blank=True, related_name='sponsor_deliverables', to='newsletter.newslettercampaign')),
                ('linked_videos', models.ManyToManyField(blank=True, related_name='sponsor_deliverables', to='content.videocontent')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='accounts.sponsorprofile')),
            ],
            options={
                'db_table': 'sponsors_deliverable',
                'ordering': ['due_date'],
            },
        ),
    ]
