# Generated by Django 6.0.2 on 2026-02-22 10:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorFunnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('awareness', 'Awareness'), ('interest', 'Interest'), ('consideration', 'Consideration'), ('donation', 'Donation'), ('retention', 'Retention'), ('advocacy', 'Advocacy')], max_length=50)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funnel_events', to='accounts.donorprofile')),
            ],
            options={
                'db_table': 'analytics_donorfunnel',
            },
        ),
        migrations.CreateModel(
            name='VideoEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('event_type', models.CharField(choices=[('play', 'Play'), ('pause', 'Pause'), ('complete', 'Complete'), ('seek', 'Seek'), ('mute', 'Mute'), ('unmute', 'Unmute')], max_length=20)),
                ('timestamp_seconds', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_events', to='content.videocontent')),
            ],
            options={
                'db_table': 'analytics_videoengagement',
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('path', models.CharField(max_length=500)),
                ('content_type', models.CharField(blank=True, max_length=50)),
                ('content_id', models.UUIDField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True)),
                ('device_type', models.CharField(blank=True, max_length=20)),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('os', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_pageview',
                'indexes': [models.Index(fields=['content_type', 'content_id'], name='analytics_p_content_89a35d_idx'), models.Index(fields=['created_at'], name='analytics_p_created_4c2b45_idx'), models.Index(fields=['path'], name='analytics_p_path_3382b5_idx')],
            },
        ),
    ]
