# Generated by Django 6.0.2 on 2026-02-22 18:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(choices=[('header', 'Header'), ('footer', 'Footer'), ('sidebar', 'Sidebar'), ('mobile', 'Mobile')], default='header', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Menus',
                'db_table': 'cms_menu',
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField(blank=True)),
                ('value_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean'), ('json', 'JSON'), ('image', 'Image')], default='text', max_length=20)),
                ('category', models.CharField(choices=[('general', 'General'), ('appearance', 'Appearance'), ('social', 'Social Media'), ('integrations', 'Integrations'), ('analytics', 'Analytics')], default='general', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
                'db_table': 'cms_site_setting',
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('widget_type', models.CharField(choices=[('hero', 'Hero Section'), ('featured_videos', 'Featured Videos'), ('latest_posts', 'Latest Posts'), ('newsletter', 'Newsletter Signup'), ('sponsors', 'Sponsors Carousel'), ('stats', 'Statistics Counter'), ('testimonials', 'Testimonials'), ('call_to_action', 'Call to Action'), ('video_grid', 'Video Grid'), ('blog_grid', 'Blog Grid'), ('custom_html', 'Custom HTML')], max_length=30)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('css_class', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cms_widget',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MediaLibrary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='cms/media/')),
                ('filename', models.CharField(max_length=255)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('audio', 'Audio')], default='image', max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('caption', models.TextField(blank=True)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('folder', models.CharField(blank=True, max_length=255)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cms_media_library',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('content_html', models.TextField(blank=True)),
                ('template', models.CharField(choices=[('default', 'Default'), ('home', 'Home'), ('about', 'About'), ('contact', 'Contact'), ('landing', 'Landing Page'), ('fullwidth', 'Full Width')], default='default', max_length=20)),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('og_image', models.ImageField(blank=True, upload_to='cms/og/')),
                ('featured_image', models.ImageField(blank=True, upload_to='cms/pages/')),
                ('video_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('show_in_nav', models.BooleanField(default=False)),
                ('nav_order', models.PositiveSmallIntegerField(default=0)),
                ('show_sidebar', models.BooleanField(default=True)),
                ('show_comments', models.BooleanField(default=False)),
                ('full_width', models.BooleanField(default=False)),
                ('background_color', models.CharField(default='#ffffff', max_length=7)),
                ('background_image', models.ImageField(blank=True, upload_to='cms/backgrounds/')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cms_page',
                'ordering': ['nav_order', '-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link_type', models.CharField(choices=[('page', 'Page'), ('url', 'Custom URL'), ('category', 'Category')], default='page', max_length=20)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('css_class', models.CharField(blank=True, max_length=100)),
                ('target_new_tab', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.category')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cms.menu')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms.menuitem')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.page')),
            ],
            options={
                'db_table': 'cms_menu_item',
                'ordering': ['order'],
            },
        ),
    ]
